name: Testes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    name: clang-format
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt install clang-format -yq
      - name: Verificar formatação com clang-format
        run: clang-format -n --ferror-limit=1 -Werror ./src/*.c