name: Testes

on:
  push:
    branches:
      - main

jobs:
  format:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Verificar formatação com clang-format
        run: clang-format -n --ferror-limit=1 -Werror --fail-on-incomplete-format ./src/**/*.c